const DEFAULT_BUTTON_WIDTH = '70%';
const DEFAULT_COMPONENT_BACKGROUND_COLOR = '#FAA0A0';
const DEFAULT_BUTTON_RIPPLE_COLOR = '#b60d8c';
const DEFAULT_BUTTON_FONT_COLOR = '#fff';
const DEFAULT_FONT_COLOR = '#042761'; 
const DEFAULT_OPTIONAL_COLOR = '#04275d';

export {
  DEFAULT_BUTTON_WIDTH,
  DEFAULT_COMPONENT_BACKGROUND_COLOR,
  DEFAULT_BUTTON_RIPPLE_COLOR,
  DEFAULT_BUTTON_FONT_COLOR,
  DEFAULT_FONT_COLOR,
  DEFAULT_OPTIONAL_COLOR
}